from typing import Dict, Any, List


class SOCPlaybookGenerator:
    """Generates automated incident response scripts and firewall rules."""

    @staticmethod
    def generate_playbook(analysis_data: Dict[str, Any]) -> Dict[str, Any]:
        headers = analysis_data.get("headers", {})
        hashes = analysis_data.get("hashes", {})
        origin_geo = analysis_data.get("origin_geo", {})
        urls = analysis_data.get("urls", [])
        attachments = analysis_data.get("attachments", [])
        homoglyph = analysis_data.get("homoglyph", {})
        case_id = analysis_data.get("case_id", "UNKNOWN")

        origin_ip = origin_geo.get("origin_ip") or analysis_data.get("hop_trace", {}).get("origin_ip", "185.120.10.5")
        from_address = headers.get("from_address", "")
        subject = headers.get("subject", "").replace('"', '\\"')
        sha256 = hashes.get("sha256", "UNKNOWN")

        # 1. Linux iptables
        iptables_cmd = f"sudo iptables -A INPUT -s {origin_ip} -j DROP -m comment --comment 'TRACEON-IOC-{case_id[:8]}'"

        # 2. AWS WAF
        aws_waf_json = {
            "Name": f"TRACEON-Block-{case_id[:8]}",
            "Scope": "REGIONAL",
            "IPSet": {
                "Addresses": [f"{origin_ip}/32"],
                "IPAddressVersion": "IPV4"
            }
        }

        # 3. Palo Alto PAN-OS CLI
        palo_alto_cmd = (
            f"set address TRACEON_IP_{case_id[:8]} ip-netmask {origin_ip}/32\n"
            f"set address-group TRACEON_BLOCKLIST static TRACEON_IP_{case_id[:8]}"
        )

        # 4. Microsoft 365 Exchange Online PowerShell Purge
        exchange_cmd = (
            f"# Connect-ExchangeOnline\n"
            f"New-ComplianceSearch -Name 'TRACEON-Purge-{case_id[:8]}' "
            f"-ExchangeLocation All -ContentMatchQuery 'Subject:\"{subject}\" AND From:\"{from_address}\"'\n"
            f"Start-ComplianceSearch -Identity 'TRACEON-Purge-{case_id[:8]}'\n"
            f"New-ComplianceSearchAction -SearchName 'TRACEON-Purge-{case_id[:8]}' -Purge -PurgeType HardDelete -Confirm:$false"
        )

        # 5. YARA Rule
        yara_rule = (
            f"rule TRACEON_Phish_{case_id[:8].replace('-', '_')} {{\n"
            f"    meta:\n"
            f"        description = \"Phishing detection rule generated by TRACEON\"\n"
            f"        case_id = \"{case_id}\"\n"
            f"        sha256 = \"{sha256}\"\n"
            f"    strings:\n"
            f"        $subject = \"{subject[:40]}\" ascii wide\n"
            f"        $sender = \"{from_address}\" ascii wide\n"
            f"    condition:\n"
            f"        all of them\n"
            f"}}"
        )

        return {
            "case_id": case_id,
            "origin_ip": origin_ip,
            "sender": from_address,
            "subject": subject,
            "iptables": iptables_cmd,
            "aws_waf": aws_waf_json,
            "palo_alto": palo_alto_cmd,
            "exchange_purge": exchange_cmd,
            "yara_rule": yara_rule
        }
